// Code generated by "stringer -type=PageID"; DO NOT EDIT.

package pages

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PActual-0]
	_ = x[PViewPort-1]
	_ = x[PRoot-2]
	_ = x[PRessources-3]
	_ = x[PPrintActions-4]
	_ = x[PDialogBox-5]
	_ = x[PK8SGet-6]
	_ = x[PK8SGetFromRoot-7]
	_ = x[PError-8]
}

const _PageID_name = "PActualPViewPortPRootPRessourcesPPrintActionsPDialogBoxPK8SGetPK8SGetFromRootPError"

var _PageID_index = [...]uint8{0, 7, 16, 21, 32, 45, 55, 62, 77, 83}

func (i PageID) String() string {
	if i < 0 || i >= PageID(len(_PageID_index)-1) {
		return "PageID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageID_name[_PageID_index[i]:_PageID_index[i+1]]
}
