Output docs/bean.gif

# Set Shell zsh
Set FontSize 18
Set Width 1000
Set Height 600
# Set Padding 40
# Set FontFamily "FantasqueSansMono Nerd Font Mono"
Set Theme "Dracula"
Set TypingSpeed 500ms
Set PlaybackSpeed 0.7
Set Padding 0

Hide
Type "clear"
Enter
Type "bean -p /home/runner/work/bean/bean/fe"
Enter
Show
Sleep 2s
Down@1s 4
Up 2
Type "/rds"
Sleep 500ms
Enter 2
Sleep 2s
Down 3
Type "p"
Sleep 3s
Backspace 1
Sleep 3s
Hide
Type "q"
