version: v1

labels:
  - label: "feature"
    sync: true
    matcher:
      title: "^(\\[FEAT\\]|feat).*"
      commits: "^feat.*"

  - label: "bugfix"
    sync: true
    matcher:
      commits: "^fix.*"

  - label: "documentation"
    sync: true
    matcher:
      title: "^(\\[DOCS\\]|docs).*"
      commits: "^docs.*"

  - label: "ci"
    sync: true
    matcher:
      title: "^(\\[CI\\]|ci).*"
      commits: "^ci.*"

  - label: "refactor"
    sync: true
    matcher:
      title: "^(\\[REFACTOR\\]|refactor).*"
      commits: "^refactor.*"

  - label: "chore"
    sync: true
    matcher:
      title: "^(\\[CHORE\\]chore).*"
      commits: "^chore.*"

  - label: "test"
    sync: true
    matcher:
      title: "^(\\[TEST\\]test).*"
      commits: "^test.*"

  - label: "perf"
    sync: true
    matcher:
      title: "^(\\[PERF\\]perf).*"
      commits: "^perf.*"

  - label: "style"
    sync: true
    matcher:
      title: "^(\\[STYLE\\]style).*"
      commits: "^style.*"

  - label: "dependencies"
    sync: true
    matcher:
      files:
        any: [ "go.mod" ]

  - label: "breaking change"
    sync: true
    matcher:
      commits: "BREAKING CHANGE:"

  - label: "bug"
    sync: true
    matcher:
      title: "^(\\[(FIX|BUG)\\]|(bug|fix)).*"
      body: "(\\n|.)*- \\[x\\] bug(\\n|.)*"