name: vhs
on:
  push:
    paths:
      - .github/bean.tape
    tags:
      - "*"
  workflow_dispatch:
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: FrangipaneTeam/provider-flexibleengine
          path: fe
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: "go install github.com/FrangipaneTeam/bean@latest"
      - uses: charmbracelet/vhs-action@v2
        with:
          path: '.github/bean.tape'
          install-fonts: true
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     add-paths: |
      #       docs/bean.gif
      #     commit-message: "docs: update bean gif"
      #     branch: update_bean_gif
      #     delete-branch: true
      #     title: "docs: update bean gif"
      #     labels: documentation, github_actions
      #     assignees: eremid
      #     reviewers: eremid
      #     draft: false
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: update generated vhs gif"
          branch: update_bean_gif
          create_branch: true
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
