name: vhs
on:
  push:
    paths:
      - .github/bean.tape
    tags:
      - "*"
  workflow_dispatch:
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: fe
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - run: "ls -l && go install github.com/FrangipaneTeam/bean@latest"
      - uses: charmbracelet/vhs-action@v1
        with:
          path: '.github/bean.tape'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            docs/bean.gif
          commit-message: "docs: update bean gif"
          branch: update_bean_gif
          delete-branch: true
          title: "docs: update bean gif"
          labels: documentation, github_actions
          assignees: eremid
          reviewers: eremid
          draft: false
